env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dDD71tRl19d9XyMQh8Y6di5CLNgGa0/w3OC2XVF2uV6IltXFepHWiEU+8FTzZiSeadTxC6am9CTr3HTXkjaaJuiA9HnPRD+QQxy0SmWqQJMnSN9v4GAvKps2Cs7aQm7/exgz+yp5sl4EHF9vrvX9P852h9GdbbU5ZIZrJKjLINM="

addons:
  coverity_scan:
    project:
      name: "frincon/openrfs"
      description: "Build submitted via Travis CI"
    notification_email: frm.rincon@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_branch


language: c
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq librsync-dev libconfuse-dev libfuse-dev check
compiler:
  - gcc
script: ./configure --disable-maintainer-mode && make && sudo make check
after_script: find tests -type f -name "*.log" -exec cat {} \;

